# Generated by Django 5.2.8 on 2026-03-19 21:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id_accion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadConsolidada',
            fields=[
                ('id_actividad_consolidada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id_escuela', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id_estrategia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_original', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo_documento_original', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_documento', models.PositiveBigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(9999999999)])),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('sexo', models.CharField(max_length=20, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('estamento', models.CharField(max_length=50, null=True)),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaEstrategia',
            fields=[
                ('id_linea_estrategia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaProyecto',
            fields=[
                ('id_linea_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_prioridad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, unique=True)),
                ('nombre_original', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadAsociada',
            fields=[
                ('id_actividad_asociada', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Consolidacion',
            fields=[
                ('id_consolidacion', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('actividad_consolidada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividadconsolidada')),
            ],
        ),
        migrations.AddField(
            model_name='accion',
            name='estrategia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estrategia'),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.persona')),
                ('semestre', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('core.persona',),
        ),
        migrations.AddField(
            model_name='escuela',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facultad'),
        ),
        migrations.AddField(
            model_name='accion',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.indicador'),
        ),
        migrations.CreateModel(
            name='EstrategiaAsociada',
            fields=[
                ('id_estrategia_asociada', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('linea_estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lineaestrategia')),
            ],
        ),
        migrations.CreateModel(
            name='AsociacionProyecto',
            fields=[
                ('id_asociacion_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('linea_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lineaproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='PrioridadAsociada',
            fields=[
                ('id_prioridad_asociada', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prioridad')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id_participacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('anio', models.PositiveIntegerField()),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sede')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tema')),
            ],
        ),
        migrations.CreateModel(
            name='TemaAsociado',
            fields=[
                ('id_tema_asociado', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividad')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tema')),
            ],
        ),
    ]
