# Generated by Django 5.2.8 on 2026-04-14 18:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id_accion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id_estrategia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LineaEstrategia',
            fields=[
                ('id_linea_estrategia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_prioridad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, unique=True)),
                ('nombre_original', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(max_length=300)),
                ('id_accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
            ],
        ),
        migrations.AddField(
            model_name='accion',
            name='estrategia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estrategia'),
        ),
        migrations.CreateModel(
            name='EstrategiaAsociada',
            fields=[
                ('id_estrategia_asociada', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('linea_estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lineaestrategia')),
            ],
        ),
        migrations.CreateModel(
            name='PrioridadAsociada',
            fields=[
                ('id_prioridad_asociada', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prioridad')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_original', models.CharField(max_length=300)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadOrganizativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('FACULTAD', 'Facultad'), ('ESCUELA', 'Escuela'), ('DEPENDENCIA', 'Dependencia Administrativa')], max_length=20)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subunidades', to='core.unidadorganizativa')),
            ],
            options={
                'verbose_name': 'Unidad Organizativa',
                'verbose_name_plural': 'Unidades Organizativas',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_original', models.CharField(max_length=300)),
                ('tipo_documento_original', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_documento', models.PositiveBigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(9999999999)])),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('sexo', models.CharField(max_length=20, null=True)),
                ('unidadOrganizativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadorganizativa')),
            ],
        ),
        migrations.CreateModel(
            name='Vinculacion',
            fields=[
                ('id_vinculacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estamento', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('id_unidad_organizativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadorganizativa')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id_participacion', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('anio', models.PositiveIntegerField()),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seccion')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sede')),
                ('vinculacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vinculacion')),
            ],
        ),
    ]
