# Generated by Django 5.2.8 on 2026-03-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidacion',
            name='actividad_consolidada',
        ),
        migrations.RemoveField(
            model_name='asociacionproyecto',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='asociacionproyecto',
            name='linea_proyecto',
        ),
        migrations.RemoveField(
            model_name='consolidacion',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='accion',
            name='indicador',
        ),
        migrations.DeleteModel(
            name='ActividadConsolidada',
        ),
        migrations.DeleteModel(
            name='AsociacionProyecto',
        ),
        migrations.DeleteModel(
            name='LineaProyecto',
        ),
        migrations.DeleteModel(
            name='Consolidacion',
        ),
        migrations.DeleteModel(
            name='Indicador',
        ),
    ]
