# Generated by Django 5.2.8 on 2025-12-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participacion',
            old_name='sedes',
            new_name='sede',
        ),
    ]
