# Generated by Django 5.2.8 on 2026-04-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='id_accion',
        ),
    ]
