# Generated by Django 5.2.8 on 2026-04-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_actividad_id_accion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='unidadOrganizativa',
        ),
    ]
