# Generated by Django 5.2.8 on 2025-12-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sedes_participacion_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tema'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
