# Generated by Django 5.2.8 on 2025-11-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_persona_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='anio',
        ),
        migrations.AddField(
            model_name='participacion',
            name='anio',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
