# Generated by Django 5.2.8 on 2025-11-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_actividad_anio_participacion_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actividadconsolidada',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='facultad',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lineaestrategia',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lineaproyecto',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_documento_original',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prioridad',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
